# TypeProf 0.12.0

# Classes
module ColorContrastCalc
  # Ref: https://github.com/ruby/rbs/blob/master/core/comparable.rbs

  module Shim
    def clamp: [A, B] (A lower_bound, B upper_bound) -> (self | A | B)
  end
end
