# TypeProf 0.12.0

# Classes
module ColorContrastCalc
  module TransparencyCalc
    include Converter::AlphaCompositing::Rgba

    def self.contrast_ratio: (untyped foreground, untyped background, ?untyped base) -> Float
    def self.opaque?: (untyped rgba) -> untyped
    def self.to_rgb: (Array[Integer] rgba) -> Array[Integer]
    def self.compose: (untyped foreground, untyped background, untyped base) -> {foreground: Array[Integer], background: Array[Integer]}
    def self.to_opaque_rgbs: (untyped foreground, untyped background, untyped base) -> Array[Array[Integer]]
  end
end
