AllCops:
  TargetRubyVersion: 2.2
Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Metrics/BlockLength:
  Exclude: ["spec/**/*", "test/**/*"]
Documentation:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/AccessModifierDeclarations:
  EnforcedStyle: inline
Naming/UncommunicativeMethodParamName:
  MinNameLength: 1
