# TypeProf 0.12.0

# Classes
module ColorContrastCalc
  class InvalidColorRepresentationError < StandardError
    def self.may_be_name?: (untyped value) -> ((Integer | false)?)
    def self.select_message_template: (untyped value) -> String
    def self.from_value: (untyped value) -> InvalidColorRepresentationError

    module Template
      RGB: String
      RGBA: String
      COLOR_NAME: String
      HEX: String
      UNEXPECTED: String
    end
  end
end
